# Speed-up using container-based infrastructure
sudo: false

language: scala

scala:
  - 2.11.8

jdk:
  - openjdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION compile

# Cache directories to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
