apiVersion: v1
kind: Service
metadata:
  name: infoblu-event-producer
  labels:
    app: infoblu-event-producer
spec:
  ports:
  - port: 9900
  selector:
    app: infoblu-event-producer
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: infoblu-event-producer-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: infoblu-event-producer
    spec:
      hostNetwork: false
      containers:
      - name: infoblu-event-producer
        image: 10.98.74.120:5000/iot-etl-producers:1.0-SNAPSHOT
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
             command: ["/bin/sh", "-c", "cat /etc/extra_hosts >> /etc/hosts"]
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - name: glusterfsvol
          mountPath: /opt/docker/conf/production.conf
          subPath: infoblu-event-producer/conf/production.conf
          readOnly: true
        - name: glusterfsvol
          mountPath: /opt/docker/conf/log4j2.xml
          subPath: infoblu-event-producer/conf/log4j2.xml
          readOnly: true
        - name: glusterfsvol
          mountPath: /opt/docker/logs
          subPath: infoblu-event-producer/conf/logs
        - name: glusterfsvol
          mountPath: /opt/docker/conf/daf.keytab
          subPath: infoblu-event-producer/conf/daf.keytab
          readOnly: true
        - name: hosts
          mountPath: /etc/extra_hosts
        - name: krb5conf
          mountPath: /etc/krb5.conf
      imagePullSecrets:
        - name: regsecret
      volumes:
      - name: glusterfsvol
        persistentVolumeClaim:
          claimName: gluster-claim
      - name: hosts
        hostPath:
          path: /etc/hosts
      - name: krb5conf
        hostPath:
          path: /etc/krb5.conf

